name: ci

on:
  push:
    branches: [main]

permissions:
  contents: write

env:
  GOPRIVATE: "github.com/gonest-dev/*"

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true
          cache-dependency-path: "**/go.sum"


      - name: Test & Coverage
        run: make ci

      - name: Commit badges
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .public/*.svg
          git diff --cached --quiet && exit 0
          git commit -m "chore: update badges [skip ci]"
          git push

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: false # Desativamos aqui para não conflitar com o cache da action de lint

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
          # A action detecta o go.work e usa o cache automaticamente
          args: --timeout=5m

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          [
            core,
            validator,
            controller,
            pipes,
            guards,
            interceptors,
            exceptions,
            swagger,
            di,
            platform,
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"


      - name: Build ${{ matrix.module }}
        run: |
          TARGET_DIR=$(find . -name "${{ matrix.module }}" -type d -not -path '*/.*' | head -n 1)
          cd "$TARGET_DIR" && go build -v ./...
